const fs = require("node:fs");
const path = require("node:path");

const repoRoot = path.resolve(__dirname, "..", "..");
const manifestPath = path.join(__dirname, "asset-manifest.json");
const componentRoot = path.join(repoRoot, "src", "CanDoItAll.Components.CanvasLib", "Components", "Shared", "Assets");
const headComponentPath = path.join(componentRoot, "CanvasLibHeadAssets.razor");
const bodyComponentPath = path.join(componentRoot, "CanvasLibBodyAssets.razor");
const staticWebAssetPrefix = "_content/CanDoItAll.Components.CanvasLib/";
const autoGeneratedBanner = "@* Auto-generated by tools/canvaslib/build-assets.cjs. Do not edit directly. *@";
const componentNamespace = "@namespace CanDoItAll.Components.CanvasLib";

function readManifest() {
  return JSON.parse(fs.readFileSync(manifestPath, "utf8"));
}

function ensureDirectory(directoryPath) {
  fs.mkdirSync(directoryPath, { recursive: true });
}

function normalizeAssetEntries(entries) {
  if (!Array.isArray(entries)) {
    return [];
  }

  return entries.map(entry => {
    if (!entry || typeof entry.source !== "string" || typeof entry.output !== "string") {
      throw new Error("Every manifest entry must define string 'source' and 'output' properties.");
    }

    return {
      source: entry.source.replaceAll("\\", "/"),
      output: entry.output.replaceAll("\\", "/")
    };
  });
}

function getSourceFilePath(sourcePath) {
  return path.join(repoRoot, "src", "CanDoItAll.Components.CanvasLib", "wwwroot", sourcePath);
}

function getOutputFilePath(outputPath) {
  if (!outputPath.startsWith(staticWebAssetPrefix)) {
    throw new Error(`Unsupported CanvasLib asset output '${outputPath}'.`);
  }

  return path.join(repoRoot, "src", "CanDoItAll.Components.CanvasLib", "wwwroot", outputPath.slice(staticWebAssetPrefix.length));
}

function ensureSourceAssetsExist(entries) {
  for (const entry of entries) {
    const absolutePath = getSourceFilePath(entry.source);
    if (!fs.existsSync(absolutePath)) {
      throw new Error(`Source asset '${entry.source}' does not exist at '${absolutePath}'.`);
    }
  }
}

function syncAsset(entry) {
  const sourcePath = getSourceFilePath(entry.source);
  const outputPath = getOutputFilePath(entry.output);
  ensureDirectory(path.dirname(outputPath));
  const content = fs.readFileSync(sourcePath, "utf8");
  const existing = fs.existsSync(outputPath)
    ? fs.readFileSync(outputPath, "utf8")
    : null;
  if (existing === content) {
    return null;
  }

  fs.writeFileSync(outputPath, content, "utf8");
  return path.relative(repoRoot, outputPath);
}

function buildHeadComponent(manifest) {
  const lines = [
    componentNamespace,
    autoGeneratedBanner,
    "@using CanDoItAll.Components.OverlayLib",
    "<OverlayLibHeadAssets />"
  ];
  for (const style of manifest.styles) {
    lines.push(`<link rel="stylesheet" href="@Assets["${style.output}"]" />`);
  }

  return `${lines.join("\r\n")}\r\n`;
}

function appendScriptSection(lines, propertyName, entries) {
  lines.push(`@if (${propertyName})`);
  lines.push("{");
  for (const entry of entries) {
    lines.push(`    <script src="@Assets["${entry.output}"]"></script>`);
  }
  lines.push("}");
}

function buildBodyComponent(manifest) {
  const lines = [
    componentNamespace,
    autoGeneratedBanner,
    "@using CanDoItAll.Components.OverlayLib"
  ];

  lines.push("@if (IncludeRuntimeAssets)");
  lines.push("{");
  lines.push(`    <OverlayLibBodyAssets IncludeRuntimeAssets="true" />`);
  for (const entry of manifest.runtimeScripts) {
    lines.push(`    <script src="@Assets["${entry.output}"]"></script>`);
  }
  lines.push("}");
  lines.push(stringEmptyLine());
  appendScriptSection(lines, "IncludePreviewAssets", manifest.previewScripts);
  lines.push(stringEmptyLine());
  appendScriptSection(lines, "IncludeCalendarAssets", manifest.calendarScripts);
  lines.push(stringEmptyLine());
  lines.push("@code {");
  lines.push("    [Parameter]");
  lines.push("    public bool IncludeRuntimeAssets { get; set; } = true;");
  lines.push(stringEmptyLine("    "));
  lines.push("    [Parameter]");
  lines.push("    public bool IncludePreviewAssets { get; set; }");
  lines.push(stringEmptyLine("    "));
  lines.push("    [Parameter]");
  lines.push("    public bool IncludeCalendarAssets { get; set; }");
  lines.push("}");

  return `${lines.join("\r\n")}\r\n`;
}

function stringEmptyLine(prefix = "") {
  return prefix;
}

function writeFileIfChanged(filePath, content) {
  ensureDirectory(path.dirname(filePath));
  const existing = fs.existsSync(filePath)
    ? fs.readFileSync(filePath, "utf8")
    : null;
  if (existing === content) {
    return false;
  }

  fs.writeFileSync(filePath, content, "utf8");
  return true;
}

const rawManifest = readManifest();
const manifest = {
  styles: normalizeAssetEntries(rawManifest.styles),
  runtimeScripts: normalizeAssetEntries(rawManifest.runtimeScripts),
  previewScripts: normalizeAssetEntries(rawManifest.previewScripts),
  calendarScripts: normalizeAssetEntries(rawManifest.calendarScripts)
};
const allAssets = [
  ...manifest.styles,
  ...manifest.runtimeScripts,
  ...manifest.previewScripts,
  ...manifest.calendarScripts
];

ensureSourceAssetsExist(allAssets);

const updatedFiles = [];
for (const entry of allAssets) {
  const updated = syncAsset(entry);
  if (updated) {
    updatedFiles.push(updated);
  }
}

if (writeFileIfChanged(headComponentPath, buildHeadComponent(manifest))) {
  updatedFiles.push(path.relative(repoRoot, headComponentPath));
}

if (writeFileIfChanged(bodyComponentPath, buildBodyComponent(manifest))) {
  updatedFiles.push(path.relative(repoRoot, bodyComponentPath));
}

if (updatedFiles.length === 0) {
  console.log("CanvasLib assets are already up to date.");
}
else {
  console.log(`Updated ${updatedFiles.join(", ")}`);
}
