const fs = require("node:fs");
const path = require("node:path");
const { renderGeneratedText } = require("../assets/generated-text.cjs");

const repoRoot = path.resolve(__dirname, "..", "..");
const manifestPath = path.join(__dirname, "asset-manifest.json");
const componentRoot = path.join(repoRoot, "src", "CanDoItAll.Components.CanvasLib", "Components", "Shared", "Assets");
const headComponentPath = path.join(componentRoot, "CanvasLibHeadAssets.razor");
const bodyComponentPath = path.join(componentRoot, "CanvasLibBodyAssets.razor");
const runtimeBodyComponentPath = path.join(componentRoot, "CanvasRuntimeBodyAssets.razor");
const staticWebAssetPrefix = "_content/CanDoItAll.Components.CanvasLib/";
const autoGeneratedBanner = "@* Auto-generated by tools/canvaslib/build-assets.cjs. Do not edit directly. *@";
const componentNamespace = "@namespace CanDoItAll.Components.CanvasLib";

function readManifest() {
  return JSON.parse(fs.readFileSync(manifestPath, "utf8"));
}

function normalizeAssetEntries(entries) {
  if (!Array.isArray(entries)) {
    return [];
  }

  return entries.map(entry => {
    if (!entry || typeof entry.source !== "string" || typeof entry.output !== "string") {
      throw new Error("Every manifest entry must define string 'source' and 'output' properties.");
    }

    return {
      source: entry.source.replaceAll("\\", "/"),
      output: entry.output.replaceAll("\\", "/")
    };
  });
}

function getSourceFilePath(sourcePath) {
  return path.join(repoRoot, "src", "CanDoItAll.Components.CanvasLib", "wwwroot", sourcePath);
}

function getOutputFilePath(outputPath) {
  if (!outputPath.startsWith(staticWebAssetPrefix)) {
    throw new Error(`Unsupported CanvasLib asset output '${outputPath}'.`);
  }

  return path.join(repoRoot, "src", "CanDoItAll.Components.CanvasLib", "wwwroot", outputPath.slice(staticWebAssetPrefix.length));
}

function ensureSourceAssetsExist(entries) {
  for (const entry of entries) {
    const absolutePath = getSourceFilePath(entry.source);
    if (!fs.existsSync(absolutePath)) {
      throw new Error(`Source asset '${entry.source}' does not exist at '${absolutePath}'.`);
    }
  }
}

function verifySynchronizedAsset(entry) {
  const sourcePath = getSourceFilePath(entry.source);
  const outputPath = getOutputFilePath(entry.output);
  if (!fs.existsSync(outputPath)) {
    throw new Error(`Generated asset '${path.relative(repoRoot, outputPath)}' is missing. Run 'node tools/canvaslib/build-assets.cjs'.`);
  }

  const sourceContent = fs.readFileSync(sourcePath, "utf8");
  const outputContent = fs.readFileSync(outputPath, "utf8");
  if (sourceContent !== outputContent) {
    throw new Error(`Generated asset '${path.relative(repoRoot, outputPath)}' is stale. Run 'node tools/canvaslib/build-assets.cjs'.`);
  }
}

function buildHeadComponent(manifest) {
  const lines = [
    componentNamespace,
    autoGeneratedBanner,
    "@using CanDoItAll.Components.OverlayLib",
    "<OverlayLibHeadAssets />"
  ];
  for (const style of manifest.styles) {
    lines.push(`<link rel="stylesheet" href="@Assets["${style.output}"]" />`);
  }

  return renderGeneratedText(lines);
}

function appendScriptSection(lines, propertyName, entries) {
  lines.push(`@if (${propertyName})`);
  lines.push("{");
  for (const entry of entries) {
    lines.push(`    <script src="@Assets["${entry.output}"]"></script>`);
  }
  lines.push("}");
}

const themeTokensScriptPath = "_content/CanDoItAll.Components.BaseLib/js/theme/theme-tokens.js";

function buildBodyComponent(manifest) {
  const lines = [
    componentNamespace,
    autoGeneratedBanner,
    "@using CanDoItAll.Components.OverlayLib"
  ];

  lines.push("@if (IncludeThemeTokens)");
  lines.push("{");
  lines.push(`    <script src="@Assets["${themeTokensScriptPath}"]"></script>`);
  lines.push("}");
  lines.push(stringEmptyLine());
  lines.push("@if (IncludeRuntimeAssets)");
  lines.push("{");
  lines.push(`    <OverlayLibBodyAssets IncludeRuntimeAssets="true" />`);
  for (const entry of manifest.runtimeScripts) {
    lines.push(`    <script src="@Assets["${entry.output}"]"></script>`);
  }
  lines.push("}");
  lines.push(stringEmptyLine());
  appendScriptSection(lines, "IncludePreviewAssets", manifest.previewScripts);
  lines.push(stringEmptyLine());
  appendScriptSection(lines, "IncludeCalendarAssets", manifest.calendarScripts);
  lines.push(stringEmptyLine());
  lines.push("@code {");
  lines.push("    [Parameter]");
  lines.push("    public bool IncludeThemeTokens { get; set; } = true;");
  lines.push(stringEmptyLine("    "));
  lines.push("    [Parameter]");
  lines.push("    public bool IncludeRuntimeAssets { get; set; } = true;");
  lines.push(stringEmptyLine("    "));
  lines.push("    [Parameter]");
  lines.push("    public bool IncludePreviewAssets { get; set; }");
  lines.push(stringEmptyLine("    "));
  lines.push("    [Parameter]");
  lines.push("    public bool IncludeCalendarAssets { get; set; }");
  lines.push("}");

  return renderGeneratedText(lines);
}

function buildRuntimeBodyComponent(manifest) {
  const runtimeEntry = manifest.runtimeScripts.find(entry => entry.source === "js/runtime/canvas-runtime.js");
  if (!runtimeEntry) {
    throw new Error("CanvasLib manifest must include js/runtime/canvas-runtime.js.");
  }

  return renderGeneratedText([
    componentNamespace,
    autoGeneratedBanner,
    `<script src="@Assets["${runtimeEntry.output}"]"></script>`
  ]);
}

function stringEmptyLine(prefix = "") {
  return prefix;
}

function verifyGeneratedFile(filePath, expectedContent) {
  if (!fs.existsSync(filePath)) {
    throw new Error(`Generated file '${path.relative(repoRoot, filePath)}' is missing. Run 'node tools/canvaslib/build-assets.cjs'.`);
  }

  const actualContent = fs.readFileSync(filePath, "utf8");
  if (actualContent !== expectedContent) {
    throw new Error(`Generated file '${path.relative(repoRoot, filePath)}' is stale. Run 'node tools/canvaslib/build-assets.cjs'.`);
  }
}

const rawManifest = readManifest();
const manifest = {
  styles: normalizeAssetEntries(rawManifest.styles),
  runtimeScripts: normalizeAssetEntries(rawManifest.runtimeScripts),
  previewScripts: normalizeAssetEntries(rawManifest.previewScripts),
  calendarScripts: normalizeAssetEntries(rawManifest.calendarScripts)
};
const allAssets = [
  ...manifest.styles,
  ...manifest.runtimeScripts,
  ...manifest.previewScripts,
  ...manifest.calendarScripts
];

ensureSourceAssetsExist(allAssets);
for (const entry of allAssets) {
  verifySynchronizedAsset(entry);
}

verifyGeneratedFile(headComponentPath, buildHeadComponent(manifest));
verifyGeneratedFile(bodyComponentPath, buildBodyComponent(manifest));
verifyGeneratedFile(runtimeBodyComponentPath, buildRuntimeBodyComponent(manifest));

console.log("CanvasLib asset sources, public outputs, and generated include components are in sync.");
