<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>CanDoItAll.Components.WebGlSandbox</AssemblyName>
    <RootNamespace>CanDoItAll.Components.WebGlSandbox</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CanDoItAll.Components.BaseLib\CanDoItAll.Components.BaseLib.csproj" />
    <ProjectReference Include="..\CanDoItAll.Components.OverlayLib\CanDoItAll.Components.OverlayLib.csproj" />
    <ProjectReference Include="..\CanDoItAll.Components.WebGlLib\CanDoItAll.Components.WebGlLib.csproj" />
    <ProjectReference Include="..\CanDoItAll.Components.WebGlRunLib\CanDoItAll.Components.WebGlRunLib.csproj" />
  </ItemGroup>

</Project>

