<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.5.2" PrivateAssets="all" />
    <PackageReference Include="bunit" Version="2.7.2" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CanDoItAll.Components.BaseLib\CanDoItAll.Components.BaseLib.csproj" />
    <ProjectReference Include="..\..\src\CanDoItAll.Components.CanvasLib\CanDoItAll.Components.CanvasLib.csproj" />
    <ProjectReference Include="..\..\src\CanDoItAll.Components.Charts\CanDoItAll.Components.Charts.csproj" />
    <ProjectReference Include="..\..\src\CanDoItAll.Components.Common\CanDoItAll.Components.Common.csproj" />
    <ProjectReference Include="..\..\src\CanDoItAll.Components.Gantt\CanDoItAll.Components.Gantt.csproj" />
    <ProjectReference Include="..\..\src\CanDoItAll.Components.Mermaid\CanDoItAll.Components.Mermaid.csproj" />
    <ProjectReference Include="..\..\src\CanDoItAll.Components.OverlayLib\CanDoItAll.Components.OverlayLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\src\CanDoItAll.Components.Mermaid\wwwroot\js\mermaidDiagram.js"
             Link="TestAssets\mermaidDiagram.js"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
