const fs = require("node:fs");
const path = require("node:path");
const { renderGeneratedText } = require("../assets/generated-text.cjs");

const repoRoot = path.resolve(__dirname, "..", "..");
const manifestPath = path.join(__dirname, "asset-manifest.json");
const componentRoot = path.join(repoRoot, "src", "CanDoItAll.Components.WebGlLib", "Components", "Shared", "Assets");
const headComponentPath = path.join(componentRoot, "WebGlLibHeadAssets.razor");
const bodyComponentPath = path.join(componentRoot, "WebGlLibBodyAssets.razor");
const staticWebAssetPrefix = "_content/CanDoItAll.Components.WebGlLib/";
const componentNamespace = "@namespace CanDoItAll.Components.WebGlLib";
const autoGeneratedBanner = "@* Auto-generated by tools/webgllib/build-assets.cjs. Do not edit directly. *@";

function readManifest() {
  return JSON.parse(fs.readFileSync(manifestPath, "utf8"));
}

function ensureDirectory(directoryPath) {
  fs.mkdirSync(directoryPath, { recursive: true });
}

function normalizeEntries(entries) {
  if (!Array.isArray(entries)) {
    return [];
  }

  return entries.map(entry => {
    if (!entry || typeof entry.source !== "string" || typeof entry.output !== "string") {
      throw new Error("Every manifest entry must define string 'source' and 'output' properties.");
    }

    return {
      source: entry.source.replaceAll("\\", "/"),
      output: entry.output.replaceAll("\\", "/"),
      runtime: typeof entry.runtime === "string" ? entry.runtime : ""
    };
  });
}

function getSourceFilePath(sourcePath) {
  return path.join(repoRoot, "src", "CanDoItAll.Components.WebGlLib", "wwwroot", sourcePath);
}

function getOutputFilePath(outputPath) {
  if (!outputPath.startsWith(staticWebAssetPrefix)) {
    throw new Error(`Unsupported WebGlLib asset output '${outputPath}'.`);
  }

  return path.join(repoRoot, "src", "CanDoItAll.Components.WebGlLib", "wwwroot", outputPath.slice(staticWebAssetPrefix.length));
}

function ensureSourceAssetsExist(entries) {
  for (const entry of entries) {
    const absolutePath = getSourceFilePath(entry.source);
    if (!fs.existsSync(absolutePath)) {
      throw new Error(`Source asset '${entry.source}' does not exist at '${absolutePath}'.`);
    }
  }
}

function syncAsset(entry) {
  const sourcePath = getSourceFilePath(entry.source);
  const outputPath = getOutputFilePath(entry.output);
  ensureDirectory(path.dirname(outputPath));
  const content = fs.readFileSync(sourcePath, "utf8");
  const existing = fs.existsSync(outputPath)
    ? fs.readFileSync(outputPath, "utf8")
    : null;
  if (existing === content) {
    return null;
  }

  fs.writeFileSync(outputPath, content, "utf8");
  return path.relative(repoRoot, outputPath);
}

function buildHeadComponent(manifest) {
  const lines = [componentNamespace, autoGeneratedBanner, "@using CanDoItAll.Components.OverlayLib", "<OverlayLibHeadAssets />"];
  for (const style of manifest.styles) {
    lines.push(`<link rel="stylesheet" href="@Assets["${style.output}"]" />`);
  }

  return renderGeneratedText(lines);
}

function buildBodyComponent(manifest) {
  const lines = [
    componentNamespace,
    autoGeneratedBanner,
    "@using CanDoItAll.Components.OverlayLib",
    "@{",
    "    var includeWorkbenchRuntimeAssets = IncludeWorkbenchRuntimeAssets ?? IncludeRuntimeAssets;",
    "    var includeSceneRuntimeAssets = IncludeSceneRuntimeAssets;",
    "    var includeAnyRuntimeAssets = includeWorkbenchRuntimeAssets || includeSceneRuntimeAssets;",
    "}",
    "@if (includeAnyRuntimeAssets)",
    "{"
  ];

  lines.push("    <OverlayLibBodyAssets IncludeRuntimeAssets=\"true\" />");
  lines.push("}");

  const workbenchScripts = manifest.runtimeScripts.filter(script => script.runtime !== "scene");
  const sceneScripts = manifest.runtimeScripts.filter(script => script.runtime === "scene");

  lines.push("@if (includeWorkbenchRuntimeAssets)");
  lines.push("{");
  for (const script of workbenchScripts) {
    lines.push(`    <script type="module" src="@Assets["${script.output}"]"></script>`);
  }
  lines.push("}");

  lines.push("@if (includeSceneRuntimeAssets)");
  lines.push("{");
  for (const script of sceneScripts) {
    lines.push(`    <script type="module" src="@Assets["${script.output}"]"></script>`);
  }
  lines.push("}");

  lines.push(stringEmptyLine());
  lines.push("@code {");
  lines.push("    [Parameter]");
  lines.push("    public bool IncludeRuntimeAssets { get; set; } = true;");
  lines.push(stringEmptyLine());
  lines.push("    [Parameter]");
  lines.push("    public bool? IncludeWorkbenchRuntimeAssets { get; set; }");
  lines.push(stringEmptyLine());
  lines.push("    [Parameter]");
  lines.push("    public bool IncludeSceneRuntimeAssets { get; set; }");
  lines.push("}");
  return renderGeneratedText(lines);
}

function stringEmptyLine() {
  return "";
}

function writeFileIfChanged(filePath, content) {
  ensureDirectory(path.dirname(filePath));
  const existing = fs.existsSync(filePath)
    ? fs.readFileSync(filePath, "utf8")
    : null;
  if (existing === content) {
    return false;
  }

  fs.writeFileSync(filePath, content, "utf8");
  return true;
}

const rawManifest = readManifest();
const manifest = {
  styles: normalizeEntries(rawManifest.styles),
  runtimeScripts: normalizeEntries(rawManifest.runtimeScripts),
  staticAssets: normalizeEntries(rawManifest.staticAssets)
};
const allAssets = [
  ...manifest.styles,
  ...manifest.runtimeScripts,
  ...manifest.staticAssets
];

ensureSourceAssetsExist(allAssets);

const updatedFiles = [];
for (const entry of allAssets) {
  const updated = syncAsset(entry);
  if (updated) {
    updatedFiles.push(updated);
  }
}

if (writeFileIfChanged(headComponentPath, buildHeadComponent(manifest))) {
  updatedFiles.push(path.relative(repoRoot, headComponentPath));
}

if (writeFileIfChanged(bodyComponentPath, buildBodyComponent(manifest))) {
  updatedFiles.push(path.relative(repoRoot, bodyComponentPath));
}

if (updatedFiles.length === 0) {
  console.log("WebGlLib assets are already up to date.");
} else {
  console.log(`Updated ${updatedFiles.join(", ")}`);
}
