const fs = require("node:fs");
const path = require("node:path");

const repoRoot = path.resolve(__dirname, "..", "..");
const manifestPath = path.join(__dirname, "asset-manifest.json");
const componentRoot = path.join(repoRoot, "src", "CanDoItAll.Components.WebGlLib", "Components", "Shared", "Assets");
const headComponentPath = path.join(componentRoot, "WebGlLibHeadAssets.razor");
const bodyComponentPath = path.join(componentRoot, "WebGlLibBodyAssets.razor");
const staticWebAssetPrefix = "_content/CanDoItAll.Components.WebGlLib/";
const componentNamespace = "@namespace CanDoItAll.Components.WebGlLib";
const autoGeneratedBanner = "@* Auto-generated by tools/webgllib/build-assets.cjs. Do not edit directly. *@";

function readManifest() {
  return JSON.parse(fs.readFileSync(manifestPath, "utf8"));
}

function normalizeEntries(entries) {
  if (!Array.isArray(entries)) {
    return [];
  }

  return entries.map(entry => {
    if (!entry || typeof entry.source !== "string" || typeof entry.output !== "string") {
      throw new Error("Every manifest entry must define string 'source' and 'output' properties.");
    }

    return {
      source: entry.source.replaceAll("\\", "/"),
      output: entry.output.replaceAll("\\", "/")
    };
  });
}

function getSourceFilePath(sourcePath) {
  return path.join(repoRoot, "src", "CanDoItAll.Components.WebGlLib", "wwwroot", sourcePath);
}

function getOutputFilePath(outputPath) {
  if (!outputPath.startsWith(staticWebAssetPrefix)) {
    throw new Error(`Unsupported WebGlLib asset output '${outputPath}'.`);
  }

  return path.join(repoRoot, "src", "CanDoItAll.Components.WebGlLib", "wwwroot", outputPath.slice(staticWebAssetPrefix.length));
}

function ensureSourceAssetsExist(entries) {
  for (const entry of entries) {
    const absolutePath = getSourceFilePath(entry.source);
    if (!fs.existsSync(absolutePath)) {
      throw new Error(`Source asset '${entry.source}' does not exist at '${absolutePath}'.`);
    }
  }
}

function verifySynchronizedAsset(entry) {
  const sourcePath = getSourceFilePath(entry.source);
  const outputPath = getOutputFilePath(entry.output);
  if (!fs.existsSync(outputPath)) {
    throw new Error(`Generated asset '${path.relative(repoRoot, outputPath)}' is missing. Run 'node tools/webgllib/build-assets.cjs'.`);
  }

  const sourceContent = fs.readFileSync(sourcePath, "utf8");
  const outputContent = fs.readFileSync(outputPath, "utf8");
  if (sourceContent !== outputContent) {
    throw new Error(`Generated asset '${path.relative(repoRoot, outputPath)}' is stale. Run 'node tools/webgllib/build-assets.cjs'.`);
  }
}

function buildHeadComponent(manifest) {
  const lines = [componentNamespace, autoGeneratedBanner];
  for (const style of manifest.styles) {
    lines.push(`<link rel="stylesheet" href="@Assets["${style.output}"]" />`);
  }

  return `${lines.join("\r\n")}\r\n`;
}

function buildBodyComponent(manifest) {
  const lines = [
    componentNamespace,
    autoGeneratedBanner,
    "@if (IncludeRuntimeAssets)",
    "{"
  ];

  for (const script of manifest.runtimeScripts) {
    lines.push(`    <script type="module" src="@Assets["${script.output}"]"></script>`);
  }

  lines.push("}");
  lines.push("");
  lines.push("@code {");
  lines.push("    [Parameter]");
  lines.push("    public bool IncludeRuntimeAssets { get; set; } = true;");
  lines.push("}");
  return `${lines.join("\r\n")}\r\n`;
}

function verifyGeneratedFile(filePath, expectedContent) {
  if (!fs.existsSync(filePath)) {
    throw new Error(`Generated file '${path.relative(repoRoot, filePath)}' is missing. Run 'node tools/webgllib/build-assets.cjs'.`);
  }

  const actualContent = fs.readFileSync(filePath, "utf8");
  if (actualContent !== expectedContent) {
    throw new Error(`Generated file '${path.relative(repoRoot, filePath)}' is stale. Run 'node tools/webgllib/build-assets.cjs'.`);
  }
}

const rawManifest = readManifest();
const manifest = {
  styles: normalizeEntries(rawManifest.styles),
  runtimeScripts: normalizeEntries(rawManifest.runtimeScripts),
  staticAssets: normalizeEntries(rawManifest.staticAssets)
};
const allAssets = [
  ...manifest.styles,
  ...manifest.runtimeScripts,
  ...manifest.staticAssets
];

ensureSourceAssetsExist(allAssets);
for (const entry of allAssets) {
  verifySynchronizedAsset(entry);
}

verifyGeneratedFile(headComponentPath, buildHeadComponent(manifest));
verifyGeneratedFile(bodyComponentPath, buildBodyComponent(manifest));

console.log("WebGlLib asset sources, public outputs, and generated include components are in sync.");
