using System.Linq.Expressions;
using CanDoItAll.Components.Common;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;

namespace CanDoItAll.Components.BaseLib;

/// <summary>
/// Base class for BaseLib form controls that must be true drop-in replacements for Blazor's
/// native <c>Input*</c> components (real <see cref="EditContext"/>/<c>ValueExpression</c> support).
/// See <c>StyledComponentBase</c> for components that only need plain <c>Value</c>/<c>ValueChanged</c>
/// binding without <c>EditForm</c> involvement.
/// </summary>
public abstract class StyledInputBase<TValue> : InputBase<TValue>
{
    /// <summary>Extra CSS classes appended to the component's own classes rather than replacing them.</summary>
    [Parameter]
    public string? Class { get; set; }

    /// <summary>Inline styles merged onto the root element.</summary>
    [Parameter]
    public string? Style { get; set; }

    /// <summary>The visual style applied to the rendered element.</summary>
    [Parameter]
    public InputLook Look { get; set; } = InputLook.Default;

    /// <summary>Vertical padding scale, independent of <see cref="Look"/>.</summary>
    [Parameter]
    public FormDensity Density { get; set; } = FormDensity.Normal;

    [CascadingParameter(Name = "FormFieldLabelId")]
    public string? FormFieldLabelId { get; set; }

    /// <summary>
    /// Backing target for a synthesized <see cref="InputBase{TValue}.ValueExpression"/> when the consumer
    /// binds via plain <c>Value</c>/<c>ValueChanged</c> (or a manual <c>@onchange</c>) instead of
    /// <c>@bind-Value</c>. Never read; it exists only so <c>FieldIdentifier.Create</c> has a real member
    /// expression to resolve, since <see cref="InputBase{TValue}"/> throws when <c>ValueExpression</c> is
    /// null regardless of whether an ancestor <see cref="EditContext"/> is present.
    /// </summary>
    private TValue _valueExpressionFallback = default!;

    /// <summary>
    /// Supplies a synthetic <see cref="InputBase{TValue}.ValueExpression"/> when the consumer didn't provide
    /// one, so plain <c>Value</c>/<c>ValueChanged</c> binding (no <c>@bind-Value</c>, no <c>EditForm</c>)
    /// works the way the old <c>StyledComponentBase</c>-based input family did. A consumer-supplied
    /// <c>ValueExpression</c> (typically auto-generated by <c>@bind-Value</c>) always wins unchanged, so
    /// real <see cref="EditContext"/> validation-css wiring is unaffected.
    /// </summary>
    public override Task SetParametersAsync(ParameterView parameters)
    {
        if (parameters.TryGetValue<Expression<Func<TValue>>>(nameof(ValueExpression), out _))
        {
            return base.SetParametersAsync(parameters);
        }

        var dictionary = new Dictionary<string, object?>();
        foreach (var parameter in parameters)
        {
            dictionary[parameter.Name] = parameter.Value;
        }

        dictionary[nameof(ValueExpression)] = (Expression<Func<TValue>>)(() => _valueExpressionFallback);
        return base.SetParametersAsync(ParameterView.FromDictionary(dictionary));
    }

    /// <summary>
    /// Merges <paramref name="baseClass"/>/<paramref name="baseStyle"/> with <see cref="Class"/>/<see cref="Style"/>,
    /// the component's unmatched attributes, and (when an <see cref="EditContext"/> is present) the field's
    /// validation-state class. Deliberately bypasses <c>InputBase&lt;TValue&gt;.CssClass</c>, which
    /// independently folds <c>AdditionalAttributes["class"]</c> + <c>EditContext.FieldCssClass</c> — using
    /// both would double-emit the consumer's <see cref="Class"/>.
    /// </summary>
    protected IReadOnlyDictionary<string, object>? BuildAttributes(string? baseClass = null, string? baseStyle = null)
    {
        var validationClass = EditContext?.FieldCssClass(FieldIdentifier);
        return ComponentAttributes.WithClassAndStyle(
            AdditionalAttributes,
            CssClassBuilder.Join(baseClass, Class, validationClass),
            CssClassBuilder.JoinStyles(baseStyle, Style));
    }

    /// <summary>Resolves <see cref="Density"/> into a CSS modifier class scoped to <paramref name="prefix"/>
    /// (e.g. <c>"ui-input"</c> or <c>"ui-select"</c>), or <c>null</c> for <see cref="FormDensity.Normal"/>.</summary>
    protected string? ResolveDensityCssClass(string prefix) => Density switch
    {
        FormDensity.Comfortable => $"{prefix}--density-comfortable",
        FormDensity.Compact => $"{prefix}--density-compact",
        _ => null
    };

    protected string? ResolveLabelledBy()
        => HasExplicitAccessibleName() ? null : FormFieldLabelId;

    protected bool HasExplicitAccessibleName()
        => AdditionalAttributes is not null
            && AdditionalAttributes.Keys.Any(key =>
                string.Equals(key, "aria-label", StringComparison.OrdinalIgnoreCase)
                || string.Equals(key, "aria-labelledby", StringComparison.OrdinalIgnoreCase));
}
